tools/gcc/git(41):ERROR:105: Unable to locate a modulefile for 'tools/gcc/git/2.8.2'
              total        used        free      shared  buff/cache   available
Mem:         128674        1854      123944          67        2876      126188
Swap:         16383           0       16383
/opt/site/sge/default/spool/node672/job_scripts/2483229: line 14: nvidia-smi: command not found
2021-06-01 21:24:52.976055: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-06-01 21:25:52.012264: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-01 21:25:52.018065: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-06-01 21:25:52.018085: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-06-01 21:25:52.018113: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (node672.pri.csf3.alces.network): /proc/driver/nvidia/version does not exist
2021-06-01 21:25:52.031468: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-01 21:25:52.032949: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-01 21:25:58.557033: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-06-01 21:25:58.558384: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2599785000 Hz
WARNING:tensorflow:AutoGraph could not transform <function custom_mse at 0x2b1b378aaa60> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
MODEL NAME = step1_224_noletter_nopretrain_no_GAP
Epoch 1/10
316/316 - 1449s - loss: 0.8578 - presence_loss: 0.4965 - coordinates_loss: 0.3613 - presence_accuracy: 0.7608
Epoch 2/10
316/316 - 1448s - loss: 0.1928 - presence_loss: 0.1621 - coordinates_loss: 0.0307 - presence_accuracy: 0.9442
Epoch 3/10
316/316 - 1439s - loss: 0.1459 - presence_loss: 0.1267 - coordinates_loss: 0.0192 - presence_accuracy: 0.9584
Epoch 4/10
316/316 - 1439s - loss: 0.1176 - presence_loss: 0.1030 - coordinates_loss: 0.0147 - presence_accuracy: 0.9677
Epoch 5/10
316/316 - 1438s - loss: 0.1151 - presence_loss: 0.1032 - coordinates_loss: 0.0119 - presence_accuracy: 0.9694
Epoch 6/10
316/316 - 1442s - loss: 0.0914 - presence_loss: 0.0800 - coordinates_loss: 0.0114 - presence_accuracy: 0.9763
Epoch 7/10
316/316 - 1446s - loss: 0.0658 - presence_loss: 0.0581 - coordinates_loss: 0.0077 - presence_accuracy: 0.9816
Epoch 8/10
316/316 - 1437s - loss: 0.0651 - presence_loss: 0.0579 - coordinates_loss: 0.0072 - presence_accuracy: 0.9825
Epoch 9/10
316/316 - 1438s - loss: 0.0696 - presence_loss: 0.0630 - coordinates_loss: 0.0066 - presence_accuracy: 0.9820
Epoch 10/10
316/316 - 1435s - loss: 0.0480 - presence_loss: 0.0428 - coordinates_loss: 0.0052 - presence_accuracy: 0.9868
2021-06-02 01:26:15.258512: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
