tools/gcc/git(41):ERROR:105: Unable to locate a modulefile for 'tools/gcc/git/2.8.2'
              total        used        free      shared  buff/cache   available
Mem:         191926        2956      182445         258        6525      187978
Swap:         16383        1013       15370
/opt/site/sge/default/spool/node922/job_scripts/2484748: line 14: nvidia-smi: command not found
2021-06-02 23:30:11.808667: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-06-02 23:30:34.791746: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-02 23:30:34.803438: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-06-02 23:30:34.803467: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-06-02 23:30:34.803500: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (node922.pri.csf3.alces.network): /proc/driver/nvidia/version does not exist
2021-06-02 23:30:34.813023: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-02 23:30:34.814523: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
2021-06-02 23:30:35.783246: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-06-02 23:30:35.783945: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2100000000 Hz
WARNING:tensorflow:AutoGraph could not transform <function custom_mse at 0x2b68ef6398b0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
MODEL NAME = step1_new_model_mobilenet
Epoch 1/10
300/300 - 3383s - loss: nan - presence_loss: nan - coordinates_loss: nan - presence_accuracy: 0.8832
Epoch 2/10
300/300 - 3343s - loss: nan - presence_loss: nan - coordinates_loss: nan - presence_accuracy: 0.5936
Epoch 3/10
300/300 - 3324s - loss: nan - presence_loss: nan - coordinates_loss: nan - presence_accuracy: 0.5964
Epoch 4/10
300/300 - 3347s - loss: nan - presence_loss: nan - coordinates_loss: nan - presence_accuracy: 0.5902
Epoch 5/10
300/300 - 3337s - loss: nan - presence_loss: nan - coordinates_loss: nan - presence_accuracy: 0.5924
2021-06-03 04:09:35.673473: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Epoch 6/10
300/300 - 3335s - loss: nan - presence_loss: nan - coordinates_loss: nan - presence_accuracy: 0.5906
Epoch 7/10
300/300 - 3327s - loss: nan - presence_loss: nan - coordinates_loss: nan - presence_accuracy: 0.5920
Epoch 8/10
300/300 - 3315s - loss: nan - presence_loss: nan - coordinates_loss: nan - presence_accuracy: 0.5951
Epoch 9/10
300/300 - 3345s - loss: nan - presence_loss: nan - coordinates_loss: nan - presence_accuracy: 0.5887
Epoch 10/10
300/300 - 3357s - loss: nan - presence_loss: nan - coordinates_loss: nan - presence_accuracy: 0.5901
