tools/gcc/git(41):ERROR:105: Unable to locate a modulefile for 'tools/gcc/git/2.8.2'
              total        used        free      shared  buff/cache   available
Mem:         112550        2207      109460         336         882      109457
Swap:         16383         853       15530
/opt/site/sge/default/spool/node772/job_scripts/2482402: line 14: nvidia-smi: command not found
2021-06-01 15:04:07.150911: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-06-01 15:04:30.674498: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-01 15:04:30.679389: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-06-01 15:04:30.679409: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-06-01 15:04:30.679434: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (node772.pri.csf3.alces.network): /proc/driver/nvidia/version does not exist
2021-06-01 15:04:30.684772: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-01 15:04:30.685794: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-01 15:04:35.620340: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-06-01 15:04:35.621713: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2400025000 Hz
WARNING:tensorflow:AutoGraph could not transform <function custom_mse at 0x2b28eddc3a60> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
MODEL NAME = step1_224_noletter_nopretrain
Epoch 1/10
313/313 - 1266s - loss: 0.4303 - presence_loss: 0.3286 - coordinates_loss: 0.1017 - presence_accuracy: 0.8404
Epoch 2/10
313/313 - 1268s - loss: 0.1525 - presence_loss: 0.1265 - coordinates_loss: 0.0260 - presence_accuracy: 0.9567
Epoch 3/10
313/313 - 1257s - loss: 0.1118 - presence_loss: 0.0945 - coordinates_loss: 0.0173 - presence_accuracy: 0.9684
Epoch 4/10
313/313 - 1261s - loss: 0.0886 - presence_loss: 0.0728 - coordinates_loss: 0.0158 - presence_accuracy: 0.9726
Epoch 5/10
313/313 - 1264s - loss: 0.0703 - presence_loss: 0.0574 - coordinates_loss: 0.0129 - presence_accuracy: 0.9819
Epoch 6/10
313/313 - 1282s - loss: 0.0616 - presence_loss: 0.0506 - coordinates_loss: 0.0110 - presence_accuracy: 0.9835
Epoch 7/10
313/313 - 1514s - loss: 0.0756 - presence_loss: 0.0641 - coordinates_loss: 0.0115 - presence_accuracy: 0.9801
Epoch 8/10
313/313 - 1740s - loss: 0.0551 - presence_loss: 0.0464 - coordinates_loss: 0.0086 - presence_accuracy: 0.9861
Epoch 9/10
